version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "17:45"

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: "17:45"