name: Running Dependency Review

on:
  pull_request:

jobs:
  review_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run dependency review
        uses: actions/dependency-review-action@v4

