# name: size-label
# on:
#     - pull_request

# jobs:
#   size-label:
#     permissions:
#       contents: read
#       pull-requests: write
#     runs-on: ubuntu-latest
#     steps:
#       - name: size-label
#         uses: "pascalgn/size-label-action@v0.5.2"
#         env:
#           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#         with:
#           sizes: >
#             {
#               "0": "XS",
#               "20": "S",
#               "50": "M",
#               "200": "L",
#               "800": "XL",
#               "2000": "XXL"
#             }


name: size-label
on:
    - pull_request
jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.label.outputs.sizeLabel }}
    steps:
      - name: size-label
        id: label
        uses: "pascalgn/size-label-action@v0.5.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  comment:
    runs-on: ubuntu-latest
    needs: label
    if: ${{ contains(needs.label.outputs.label, 'XL') }}
    steps:
      - run: echo "Too big PR"