name: "Labeler"
on:
  - pull_request

jobs:
    pr-labeler:
      permissions:
        contents: read
        pull-requests: write
      runs-on: ubuntu-latest
      steps:
      - uses: actions/labeler@v4.0.4
        with:
          sync-labels: true
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
    
    size-label:
      runs-on: ubuntu-latest
      steps:
        - name: size-label
          uses: "pascalgn/size-label-action@v0.4.3"
          env:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          with:
            sizes: >
              {
                "0": "XS",
                "20": "S",
                "50": "M",
                "250": "Too Large"
              }