name: Pull Request Lint

on:
  - pull_request

jobs:
  lint_and_label:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^[A-Z].*\.$' # Regex the title should match.
          prefix_case_sensitive: true # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 50 # Max length of the title
          # github_token: ${{ github.token }} # Default: ${{ github.token }}