name: Pull Request Title Lint

on:
  - pull_request

jobs:
  lint_title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: PR Title Lint
        uses: morrisoncole/pr-lint-action@v1.7.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"  
          title-regex: .github/pr-lint-config.yml
