name: Running Validate PR Title

on:
  - pull_request

jobs:
  lint_title:
    runs-on: ubuntu-latest
    steps:
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '^(?![0-9A-Z@#$%^&*!~]).*$'
          prefix_case_sensitive: false
          min_length: 5 
          max_length: 50
