name: Access server
on: push
jobs:
  access_server:
    name: Access server
    runs-on: ubuntu-latest
    steps:
      - name: Create a file
        uses: appleboy/ssh-action@master
        with:
          host: 34.105.137.35
          username: golnar
          key: ${{ secrets.SSH_PRIVATEKEY }}
          script: echo hello world > hello.txt
