# .github/workflows/main.yml
name: CI Workflow

on:
  push:

jobs:
  job1:
    name: First Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run first set of tasks
        run: echo "Running Job 1 tasks"

  job2:
    name: Second Job
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run second set of tasks
        run: echo "Running Job 2 tasks"
