name: PR Labeler
on:
  pull_request:

permissions:
  contents: read

jobs:
  pr-labeler:
    # permissions:
    #   contents: read # for TimonVS/pr-labeler-action to read config file
    #   pull-requests: write # for TimonVS/pr-labeler-action to add labels in PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
          repo-token: ${{ secrets.SSH_PRIVATEKEY }}
          
