name: "Pull Request Labeler"
on:
  pull_request:
    types:
      - opened
      - edited

permissions:
  contents: read

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: actions/labeler@v4
        with:
          configuration-path: .github/pr_labeler.yml
          repo-token: "${{ secrets.SSH_PRIVATEKEY }}"
