name: PR Labeler

on:
  pull_request:

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: PR Labeler
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.SSH_PRIVATEKEY }}
          configuration-path: .github/pr_labeler.yml
