name: PR Labeler

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: PR Labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{secrets.SSH_PRIVATEKEY}}
          configuration-path: .github/labeler.yml
