name: "Team Lable"

on:
  push:

permissions:
  contents: read
  pull-requests: write

jobs:
  team-labeler:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
    - uses: JulienKode/team-labeler-action@v1.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"  