name: "Running Team Lable"

on:
- pull_request

permissions:
  contents: read
  pull-requests: write

jobs:
  team-labeler:
    name: Team Labeler
    runs-on: ubuntu-latest
    steps:
    - uses: JulienKode/team-labeler-action@v1.1.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"  