name: "Running Validate Semantic PR Title"

on:
  - pull_request

permissions:
  pull-requests: read

jobs:
  semantic_pr_title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"  