name: Add Codecov 

on:
  pull_request:

jobs:
  review_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hakimehmordadi/Databases

